/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Autor.OpcionesAutor;
import Boleta.BuscarBoleta;
import Boleta.BuscarFolioBoleta;
import Boleta.EliminarBoleta;
import Boleta.InsertarBoleta;
import Boleta.MostrarTodasBoletas;
import Categoria.OpcionesCategoria;
import Cliente.BuscarCliente;
import Cliente.BuscarRutCliente;
import Cliente.EliminarCliente;
import Cliente.InsertarCliente;
import Cliente.MostrarTodosCliente;
import Distribuidor.BuscarDistribuidor;
import Distribuidor.BuscarDistribuidorRut;
import Distribuidor.EliminarDistribuidor;
import Distribuidor.InsertarDistribuidor;
import Distribuidor.MostrarTodosDistribuidores;
import Editorial.OpcionesEditorial;
import Factura.BuscarFactura;
import Factura.BuscarFolioFactura;
import Factura.EliminarFactura;
import Factura.InsertarFactura;
import Factura.MostrarTodasFacturas;
import Idioma.OpcionesIdioma;
import Libro.InsertarLibro;
import Libro.BuscarLibroCodigo;
import Libro.EliminarLibro;
import Libro.BuscarLibro;
import Libro.Entrega;
import Libro.InsertarISBN;
import Libro.MostrarTodosLibros;
import MostrarClienteTrabajador.MostrarCliente;
import MostrarClienteTrabajador.MostrarTrabajador;
import MostrarVentasArriendoCompras.Arriendo;
import MostrarVentasArriendoCompras.Compras;
import MostrarVentasArriendoCompras.Ventas;
import Trabajador.BuscarRutTrabajador;
import Trabajador.BuscarTrabajador;
import Trabajador.EliminarTrabajador;
import Trabajador.InsertarTrabajador;
import Trabajador.MostrarTodosTrabajador;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 20017181-0
 */
public class MenuOpciones extends javax.swing.JFrame {

    /**
     * Creates new form MenuOpciones
     */
    conexion x;
    public MenuOpciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        Date now = new Date(System.currentTimeMillis());
        calendarioArriendo.setMaxSelectableDate(now);
        calendarioArriendo.setMinSelectableDate(now);
        calendarioDevolucion.setMinSelectableDate(now);
        
        ArrayList <String> listaBoletas=new ArrayList <String>();
        listaBoletas=llenarListaBoletas();
        
        for(int i=0; i<listaBoletas.size(); i++)
        {
            boxBoletaVenta.addItem(listaBoletas.get(i));
        }
        
        ArrayList <String> listaFacturas=new ArrayList <String>();
        listaFacturas=llenarListaFacturas();

        for(int is=0; is<listaFacturas.size(); is++)
        {
             ComboBoxFactura.addItem(listaFacturas.get(is));
        }
        
        ArrayList <String> listaLibros=new ArrayList <String>();
        listaLibros=llenarListaLibros();
        for(int is=0; is<listaLibros.size(); is++)
        {
             ComboBoxLibro.addItem(listaLibros.get(is));
        }
        
        ArrayList <String> listaClientes=new ArrayList <String>();
        listaClientes=llenarListaClientes();
        for(int is=0; is<listaClientes.size(); is++)
        {
             ComboCliente.addItem(listaClientes.get(is));
        }
        
        ArrayList <String> listaTrabajador=new ArrayList <String>();
        listaTrabajador=llenarListaTrabajador();
        for(int is=0; is<listaTrabajador.size(); is++)
        {
             ComboTrabajador.addItem(listaTrabajador.get(is));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public ArrayList llenarListaBoletas()
    {
        ArrayList <String> lista=new ArrayList <String>();
        x=new conexion();
        Connection cn=x.getConnection();
        try 
        {
            Statement st=cn.createStatement();
            ResultSet rs;
            rs=st.executeQuery("select folio_boleta from mydb.boleta where etsado=''");
            
            while(rs.next())
            {
                lista.add(rs.getString(1));
            }
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(Nuevo_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        return lista;
    }
    
        public ArrayList llenarListaClientes()
    {
        ArrayList <String> lista=new ArrayList <String>();
        x=new conexion();
        Connection cn=x.getConnection();
        try 
        {
            Statement st=cn.createStatement();
            ResultSet rs;
            rs=st.executeQuery("select rut_cliente from cliente");
            
            while(rs.next())
            {
                lista.add(rs.getString(1));
            }
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(Nuevo_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        return lista;
    }
    
        public ArrayList llenarListaTrabajador()
    {
        ArrayList <String> lista=new ArrayList <String>();
        x=new conexion();
        Connection cn=x.getConnection();
        try 
        {
            Statement st=cn.createStatement();
            ResultSet rs;
            rs=st.executeQuery("select rut_trabajador from mydb.trabajador");
            
            while(rs.next())
            {
                lista.add(rs.getString(1));
            }
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(Nuevo_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        return lista;
    }
    
    public ArrayList llenarListaLibros()
    {
        ArrayList <String> lista=new ArrayList <String>();
        x=new conexion();
        Connection cn=x.getConnection();
        try 
        {
            Statement st=cn.createStatement();
            ResultSet rs;
            rs=st.executeQuery("select numero_serie from libro where estado='Disponible'");
            
            while(rs.next())
            {
                lista.add(rs.getString(1));
            }
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(Nuevo_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        return lista;
    }
    
    public ArrayList llenarListaFacturas()
    {
        ArrayList <String> lista=new ArrayList <String>();
        x=new conexion();
        Connection cn=x.getConnection();
        try 
        {
            Statement st=cn.createStatement();
            ResultSet rs;
            rs=st.executeQuery("select folio_factura from mydb.factura where estado=''");
            
            while(rs.next())
            {
                lista.add(rs.getString(1));
            }
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(Nuevo_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        return lista;
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesLibro = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        radioInsertar1 = new javax.swing.JRadioButton();
        radioModificar1 = new javax.swing.JRadioButton();
        radioEliminar1 = new javax.swing.JRadioButton();
        radioBuscar1 = new javax.swing.JRadioButton();
        radioMostrarTodos1 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        radioInsertar2 = new javax.swing.JRadioButton();
        radioModificar2 = new javax.swing.JRadioButton();
        radioEliminar2 = new javax.swing.JRadioButton();
        radioBuscar2 = new javax.swing.JRadioButton();
        radioMostrarTodos2 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        radioInsertar5 = new javax.swing.JRadioButton();
        radioModificar5 = new javax.swing.JRadioButton();
        radioEliminar5 = new javax.swing.JRadioButton();
        radioBuscar5 = new javax.swing.JRadioButton();
        radioMostrarTodos5 = new javax.swing.JRadioButton();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        radioMostrarTodos3 = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        radioBuscar3 = new javax.swing.JRadioButton();
        radioEliminar3 = new javax.swing.JRadioButton();
        radioModificar3 = new javax.swing.JRadioButton();
        radioInsertar3 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        radioInsertar4 = new javax.swing.JRadioButton();
        radioModificar4 = new javax.swing.JRadioButton();
        radioEliminar4 = new javax.swing.JRadioButton();
        radioBuscar4 = new javax.swing.JRadioButton();
        radioMostrarTodos4 = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        boxBoletaVenta = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        AgregarBoleta = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtTrabajadorVenta = new javax.swing.JTextField();
        txtClienteVenta = new javax.swing.JTextField();
        txtLibroVenta = new javax.swing.JTextField();
        btnBuscarDatos = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ComboBoxLibro = new javax.swing.JComboBox<>();
        ComboCliente = new javax.swing.JComboBox<>();
        ComboTrabajador = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();
        btnCancelarArriendo = new javax.swing.JButton();
        calendarioArriendo = new com.toedter.calendar.JDateChooser();
        calendarioDevolucion = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ComboBoxFactura = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        AgregarFactura = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtDistribuidorCompra = new javax.swing.JTextField();
        txtLibroCompra = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        radioInsertar = new javax.swing.JRadioButton();
        radioModificar = new javax.swing.JRadioButton();
        radioEliminar = new javax.swing.JRadioButton();
        radioBuscar = new javax.swing.JRadioButton();
        radioMostrarTodos = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAutor = new javax.swing.JButton();
        btnCategoria = new javax.swing.JButton();
        btnIdioma = new javax.swing.JButton();
        btnEditorial = new javax.swing.JButton();
        btnISBN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        botonesLibro.add(radioInsertar1);
        radioInsertar1.setText("Insertar Distribuidor");

        botonesLibro.add(radioModificar1);
        radioModificar1.setText("Modificar Distribuidor");

        botonesLibro.add(radioEliminar1);
        radioEliminar1.setText("Eliminar Distribuidor");
        radioEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEliminar1ActionPerformed(evt);
            }
        });

        botonesLibro.add(radioBuscar1);
        radioBuscar1.setText("Buscar Distribuidor");

        botonesLibro.add(radioMostrarTodos1);
        radioMostrarTodos1.setText("Mostrar Todos");
        radioMostrarTodos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMostrarTodos1ActionPerformed(evt);
            }
        });

        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton12.setText("Cerrar Sesión");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioInsertar1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton3))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(radioModificar1)
                        .addComponent(radioBuscar1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radioEliminar1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radioMostrarTodos1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(479, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(radioInsertar1)
                .addGap(18, 18, 18)
                .addComponent(radioModificar1)
                .addGap(18, 18, 18)
                .addComponent(radioEliminar1)
                .addGap(18, 18, 18)
                .addComponent(radioBuscar1)
                .addGap(18, 18, 18)
                .addComponent(radioMostrarTodos1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Distribuidores", jPanel2);

        botonesLibro.add(radioInsertar2);
        radioInsertar2.setText("Insertar Factura");

        botonesLibro.add(radioModificar2);
        radioModificar2.setText("Modificar Factura");

        botonesLibro.add(radioEliminar2);
        radioEliminar2.setText("Eliminar Factura");
        radioEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEliminar2ActionPerformed(evt);
            }
        });

        botonesLibro.add(radioBuscar2);
        radioBuscar2.setText("Buscar Factura");

        botonesLibro.add(radioMostrarTodos2);
        radioMostrarTodos2.setText("Mostrar Todas");
        radioMostrarTodos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMostrarTodos2ActionPerformed(evt);
            }
        });

        jButton4.setText("Aceptar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioInsertar2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton4))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(radioModificar2)
                        .addComponent(radioBuscar2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radioEliminar2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radioMostrarTodos2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(495, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(radioInsertar2)
                .addGap(18, 18, 18)
                .addComponent(radioModificar2)
                .addGap(18, 18, 18)
                .addComponent(radioEliminar2)
                .addGap(18, 18, 18)
                .addComponent(radioBuscar2)
                .addGap(18, 18, 18)
                .addComponent(radioMostrarTodos2)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Facturas", jPanel3);

        botonesLibro.add(radioInsertar5);
        radioInsertar5.setText("Insertar Boleta");

        botonesLibro.add(radioModificar5);
        radioModificar5.setText("Modificar Boleta");

        botonesLibro.add(radioEliminar5);
        radioEliminar5.setText("Eliminar Boleta");
        radioEliminar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEliminar5ActionPerformed(evt);
            }
        });

        botonesLibro.add(radioBuscar5);
        radioBuscar5.setText("Buscar Boleta");

        botonesLibro.add(radioMostrarTodos5);
        radioMostrarTodos5.setText("Mostrar Todas");
        radioMostrarTodos5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMostrarTodos5ActionPerformed(evt);
            }
        });

        jButton7.setText("Aceptar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioInsertar5)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton7))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(radioModificar5)
                        .addComponent(radioBuscar5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radioEliminar5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radioMostrarTodos5, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(503, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(radioInsertar5)
                .addGap(18, 18, 18)
                .addComponent(radioModificar5)
                .addGap(18, 18, 18)
                .addComponent(radioEliminar5)
                .addGap(18, 18, 18)
                .addComponent(radioBuscar5)
                .addGap(18, 18, 18)
                .addComponent(radioMostrarTodos5)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Boleta", jPanel6);

        botonesLibro.add(radioMostrarTodos3);
        radioMostrarTodos3.setText("Mostrar Todos");
        radioMostrarTodos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMostrarTodos3ActionPerformed(evt);
            }
        });

        jButton5.setText("Aceptar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        botonesLibro.add(radioBuscar3);
        radioBuscar3.setText("Buscar Cliente");

        botonesLibro.add(radioEliminar3);
        radioEliminar3.setText("Eliminar Cliente");
        radioEliminar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEliminar3ActionPerformed(evt);
            }
        });

        botonesLibro.add(radioModificar3);
        radioModificar3.setText("Modificar Cliente");

        botonesLibro.add(radioInsertar3);
        radioInsertar3.setText("Insertar Cliente");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioInsertar3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton5))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(radioModificar3)
                        .addComponent(radioBuscar3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radioEliminar3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radioMostrarTodos3, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(499, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(radioInsertar3)
                .addGap(18, 18, 18)
                .addComponent(radioModificar3)
                .addGap(18, 18, 18)
                .addComponent(radioEliminar3)
                .addGap(18, 18, 18)
                .addComponent(radioBuscar3)
                .addGap(18, 18, 18)
                .addComponent(radioMostrarTodos3)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cliente", jPanel4);

        botonesLibro.add(radioInsertar4);
        radioInsertar4.setText("Insertar Trabajador");

        botonesLibro.add(radioModificar4);
        radioModificar4.setText("Modificar Trabajador");

        botonesLibro.add(radioEliminar4);
        radioEliminar4.setText("Eliminar Trabajador");
        radioEliminar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEliminar4ActionPerformed(evt);
            }
        });

        botonesLibro.add(radioBuscar4);
        radioBuscar4.setText("Buscar Trabajador");

        botonesLibro.add(radioMostrarTodos4);
        radioMostrarTodos4.setText("Mostrar Todos");
        radioMostrarTodos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMostrarTodos4ActionPerformed(evt);
            }
        });

        jButton6.setText("Aceptar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioInsertar4)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton6))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(radioModificar4)
                        .addComponent(radioBuscar4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radioEliminar4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radioMostrarTodos4, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(479, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(radioInsertar4)
                .addGap(18, 18, 18)
                .addComponent(radioModificar4)
                .addGap(18, 18, 18)
                .addComponent(radioEliminar4)
                .addGap(18, 18, 18)
                .addComponent(radioBuscar4)
                .addGap(18, 18, 18)
                .addComponent(radioMostrarTodos4)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Trabajador", jPanel5);

        jLabel8.setText("Boleta Asociada");

        jButton9.setText("Aceptar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        boxBoletaVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boleta" }));

        jLabel9.setText("Cliente Asociado");

        jLabel10.setText("Libro Vendido");

        jLabel13.setText("¿No esta la boleta? Agregala!");

        AgregarBoleta.setText("Agregar");
        AgregarBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBoletaActionPerformed(evt);
            }
        });

        jLabel14.setText("Trabajador Asociado");

        txtTrabajadorVenta.setEnabled(false);

        txtClienteVenta.setEnabled(false);

        txtLibroVenta.setEnabled(false);

        btnBuscarDatos.setText("Buscar Datos");
        btnBuscarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDatosActionPerformed(evt);
            }
        });

        jButton15.setText("Mostrar Ventas");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel5.setText("¿Quieres ver las ventas? Pincha aqui");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(btnBuscarDatos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLibroVenta)
                            .addComponent(txtClienteVenta)
                            .addComponent(txtTrabajadorVenta)
                            .addComponent(boxBoletaVenta, 0, 185, Short.MAX_VALUE))))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(AgregarBoleta))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton15))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel5))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel13)))
                .addGap(75, 75, 75))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AgregarBoleta)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton15))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxBoletaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLibroVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtClienteVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTrabajadorVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addGap(30, 30, 30)
                .addComponent(btnBuscarDatos)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(btnCancelar))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Venta", jPanel7);

        jLabel15.setText("Libro Arrendado");

        jLabel17.setText("Fecha de Arriendo");

        jLabel18.setText("Fecha Devolucion Estimada");

        ComboBoxLibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libro" }));

        ComboCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente" }));

        ComboTrabajador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trabajador" }));

        btnAceptar.setText("Arrendar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelarArriendo.setText("Cancelar");
        btnCancelarArriendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarArriendoActionPerformed(evt);
            }
        });

        jLabel6.setText("Cliente involucrado");

        jLabel11.setText("Trabajador involucrado");

        jButton11.setText("Entrega");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton13.setText("Ver");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Ver");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel12.setText("Mire los arriendos aqui");

        jButton16.setText("Mostrar Arriendos");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addGap(44, 44, 44)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(ComboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ComboBoxLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(ComboTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(calendarioDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calendarioArriendo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton16)
                    .addComponent(jLabel12))
                .addGap(57, 57, 57))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addGap(27, 27, 27)
                        .addComponent(btnCancelarArriendo))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(ComboBoxLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(calendarioArriendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(calendarioDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6)
                        .addComponent(jButton16)))
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButton13))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jButton14))
                .addGap(32, 32, 32)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelarArriendo))
                .addGap(18, 18, 18)
                .addComponent(jButton11)
                .addGap(0, 147, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Arriendo", jPanel9);

        jLabel1.setText("Libro Comprado");

        jLabel3.setText("Distribuidor Asociado");

        jLabel4.setText("Factura Asociada");

        ComboBoxFactura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Factura" }));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton8.setText("Cancelar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        AgregarFactura.setText("Agregar");
        AgregarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarFacturaActionPerformed(evt);
            }
        });

        jLabel7.setText("¿No esta la factura? Agregala!");

        txtDistribuidorCompra.setEnabled(false);
        txtDistribuidorCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDistribuidorCompraActionPerformed(evt);
            }
        });

        txtLibroCompra.setEnabled(false);

        jButton10.setText("Buscar Datos");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel16.setText("Mira las compras aqui");

        jButton17.setText("Mostrar Compras");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(109, 372, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jButton10)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDistribuidorCompra)
                    .addComponent(ComboBoxFactura, 0, 143, Short.MAX_VALUE)
                    .addComponent(txtLibroCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(AgregarFactura)
                                .addGap(47, 47, 47)))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton17)
                            .addComponent(jLabel16))
                        .addGap(78, 78, 78))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtLibroCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDistribuidorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(25, 25, 25)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton8)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(39, 39, 39))
                            .addComponent(AgregarFactura, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton17)))
                .addContainerGap(213, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Compra", jPanel8);

        botonesLibro.add(radioInsertar);
        radioInsertar.setText("Insertar Libro");

        botonesLibro.add(radioModificar);
        radioModificar.setText("Modificar Libro");

        botonesLibro.add(radioEliminar);
        radioEliminar.setText("Eliminar Libro");

        botonesLibro.add(radioBuscar);
        radioBuscar.setText("Buscar Libro");

        botonesLibro.add(radioMostrarTodos);
        radioMostrarTodos.setText("Mostrar Todos");
        radioMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMostrarTodosActionPerformed(evt);
            }
        });

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("¿Que desea modificar?");

        btnAutor.setText("Autor");
        btnAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorActionPerformed(evt);
            }
        });

        btnCategoria.setText("Categoria");
        btnCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaActionPerformed(evt);
            }
        });

        btnIdioma.setText("Idioma");
        btnIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIdiomaActionPerformed(evt);
            }
        });

        btnEditorial.setText("Editorial");
        btnEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditorialActionPerformed(evt);
            }
        });

        btnISBN.setText("ISBN");
        btnISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnISBNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(radioMostrarTodos)
                        .addComponent(radioModificar)
                        .addComponent(radioBuscar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radioEliminar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radioInsertar, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnEditorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCategoria)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(40, 40, 40)))
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnISBN)
                        .addGap(145, 145, 145))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAutor)
                            .addComponent(btnCategoria))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIdioma)
                            .addComponent(btnEditorial))
                        .addGap(18, 18, 18)
                        .addComponent(btnISBN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(radioInsertar)
                        .addGap(18, 18, 18)
                        .addComponent(radioModificar)
                        .addGap(18, 18, 18)
                        .addComponent(radioEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(radioBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(radioMostrarTodos)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Libros", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(radioInsertar.isSelected())
        {
            InsertarLibro x=new InsertarLibro();
            x.setVisible(true);
            dispose();
        }
        if(radioModificar.isSelected())
        {
            BuscarLibroCodigo x=new BuscarLibroCodigo();
            x.setVisible(true);
            dispose();
        }
        if(radioEliminar.isSelected())
        {
            EliminarLibro x=new EliminarLibro();
            x.setVisible(true);
            dispose();
        }
        if(radioBuscar.isSelected())
        {
            BuscarLibro x=new BuscarLibro();
            x.setVisible(true);
            dispose();
        }
        if(radioMostrarTodos.isSelected())
        {
            MostrarTodosLibros x=new MostrarTodosLibros();
            x.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void radioMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMostrarTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMostrarTodosActionPerformed

    private void btnAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorActionPerformed
        // TODO add your handling code here:
        OpcionesAutor x=new OpcionesAutor();
        x.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAutorActionPerformed

    private void btnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaActionPerformed
        // TODO add your handling code here:
        OpcionesCategoria x=new OpcionesCategoria();
        x.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCategoriaActionPerformed

    private void btnIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIdiomaActionPerformed
        // TODO add your handling code here:
        OpcionesIdioma x=new OpcionesIdioma();
        x.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnIdiomaActionPerformed

    private void btnEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditorialActionPerformed
        // TODO add your handling code here:
        OpcionesEditorial x=new OpcionesEditorial();
        x.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEditorialActionPerformed

    private void radioMostrarTodos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMostrarTodos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMostrarTodos1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(radioInsertar1.isSelected())
        {
            InsertarDistribuidor x=new InsertarDistribuidor();
            x.setVisible(true);
            dispose();
        }
        if(radioModificar1.isSelected())
        {
            BuscarDistribuidorRut x=new BuscarDistribuidorRut();
            x.setVisible(true);
            dispose();
        }
        if(radioEliminar1.isSelected())
        {
            EliminarDistribuidor x=new EliminarDistribuidor();
            x.setVisible(true);
            dispose();
        }
        if(radioBuscar1.isSelected())
        {
            BuscarDistribuidor x=new BuscarDistribuidor();
            x.setVisible(true);
            dispose();
        }
        if(radioMostrarTodos1.isSelected())
        {
            MostrarTodosDistribuidores x=new MostrarTodosDistribuidores();
            x.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void radioEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEliminar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioEliminar1ActionPerformed

    private void radioEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEliminar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioEliminar2ActionPerformed

    private void radioMostrarTodos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMostrarTodos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMostrarTodos2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(radioInsertar2.isSelected())
        {
            InsertarFactura x=new InsertarFactura();
            x.setVisible(true);
            dispose();
        }
        if(radioModificar2.isSelected())
        {
            BuscarFolioFactura x=new BuscarFolioFactura();
            x.setVisible(true);
            dispose();
        }
        if(radioEliminar2.isSelected())
        {
            EliminarFactura x=new EliminarFactura();
            x.setVisible(true);
            dispose();
        }
        if(radioBuscar2.isSelected())
        {
            BuscarFactura x=new BuscarFactura();
            x.setVisible(true);
            dispose();
        }
        if(radioMostrarTodos2.isSelected())
        {
            MostrarTodasFacturas x=new MostrarTodasFacturas();
            x.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void radioEliminar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEliminar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioEliminar3ActionPerformed

    private void radioMostrarTodos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMostrarTodos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMostrarTodos3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(radioInsertar3.isSelected())
        {
            InsertarCliente x=new InsertarCliente();
            x.setVisible(true);
            dispose();
        }
        if(radioModificar3.isSelected())
        {
            BuscarRutCliente x=new BuscarRutCliente();
            x.setVisible(true);
            dispose();
        }
        if(radioEliminar3.isSelected())
        {
            EliminarCliente x=new EliminarCliente();
            x.setVisible(true);
            dispose();
        }
        if(radioBuscar3.isSelected())
        {
            BuscarCliente x=new BuscarCliente();
            x.setVisible(true);
            dispose();
        }
        if(radioMostrarTodos3.isSelected())
        {
            MostrarTodosCliente x=new MostrarTodosCliente();
            x.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void radioEliminar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEliminar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioEliminar4ActionPerformed

    private void radioMostrarTodos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMostrarTodos4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMostrarTodos4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(radioInsertar4.isSelected())
        {
            InsertarTrabajador x=new InsertarTrabajador();
            x.setVisible(true);
            dispose();
        }
        if(radioModificar4.isSelected())
        {
            BuscarRutTrabajador x=new BuscarRutTrabajador();
            x.setVisible(true);
            dispose();
        }
        if(radioEliminar4.isSelected())
        {
            EliminarTrabajador x=new EliminarTrabajador();
            x.setVisible(true);
            dispose();
        }
        if(radioBuscar4.isSelected())
        {
            BuscarTrabajador x=new BuscarTrabajador();
            x.setVisible(true);
            dispose();
        }
        if(radioMostrarTodos4.isSelected())
        {
            MostrarTodosTrabajador x=new MostrarTodosTrabajador();
            x.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void radioEliminar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEliminar5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioEliminar5ActionPerformed

    private void radioMostrarTodos5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMostrarTodos5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMostrarTodos5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(radioInsertar5.isSelected())
        {
            InsertarBoleta x=new InsertarBoleta();
            x.setVisible(true);
            dispose();
        }
        if(radioModificar5.isSelected())
        {
            BuscarFolioBoleta x=new BuscarFolioBoleta();
            x.setVisible(true);
            dispose();
        }
        if(radioEliminar5.isSelected())
        {
            EliminarBoleta x=new EliminarBoleta();
            x.setVisible(true);
            dispose();
        }
        if(radioBuscar5.isSelected())
        {
            BuscarBoleta x=new BuscarBoleta();
            x.setVisible(true);
            dispose();
        }
        if(radioMostrarTodos5.isSelected())
        {
            MostrarTodasBoletas x=new MostrarTodasBoletas();
            x.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        ComboBoxFactura.setSelectedIndex(0);
        txtLibroCompra.setText("");
        txtDistribuidorCompra.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void AgregarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarFacturaActionPerformed
        // TODO add your handling code here:
        InsertarFactura x=new InsertarFactura();
        x.setVisible(true);
        dispose();
    }//GEN-LAST:event_AgregarFacturaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        boxBoletaVenta.setSelectedIndex(0);
        txtLibroVenta.setText("");
        txtTrabajadorVenta.setText("");
        txtClienteVenta.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void AgregarBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBoletaActionPerformed
        // TODO add your handling code here:
        InsertarBoleta x=new InsertarBoleta();
        x.setVisible(true);
        dispose();
    }//GEN-LAST:event_AgregarBoletaActionPerformed

    private void btnCancelarArriendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarArriendoActionPerformed
        // TODO add your handling code here:
        calendarioArriendo.setCalendar(null);
        calendarioDevolucion.setCalendar(null);
        ComboBoxLibro.setSelectedIndex(0);
        ComboCliente.setSelectedIndex(0);
        ComboTrabajador.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnCancelarArriendoActionPerformed

    private void btnBuscarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDatosActionPerformed
        // TODO add your handling code here:
        if(boxBoletaVenta.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null, "No selecciono una boleta para la venta");
        }
        else
        {
            Connection cn=x.getConnection();
            try
            {
                Statement st=cn.createStatement();
                ResultSet rs;
                int libro=0;
                String cliente = null, trabajador = null;
                
                rs=st.executeQuery("select * from boleta where folio_boleta="+boxBoletaVenta.getSelectedItem()+"");
                if(rs.next())
                {
                    libro=Integer.parseInt(rs.getString(4));
                    cliente=rs.getString(6);
                    trabajador=rs.getString(5);
                }
                rs=st.executeQuery("select titutlo from libro where numero_serie="+libro+"");
                if(rs.next())
                {
                    txtLibroVenta.setText(rs.getString(1));
                }
                rs=st.executeQuery("select nombre_persona, apellido_paterno, apellido_materno from persona where Cliente_rut_cliente='"+cliente+"'");
                if(rs.next())
                {
                    txtClienteVenta.setText(rs.getString(1)+" "+rs.getString(2)+" "+rs.getString(3));
                }
                rs=st.executeQuery("select nombre_persona, apellido_paterno, apellido_materno from persona where Trabajador_rut_trabajador='"+trabajador+"'");
                if(rs.next())
                {
                    txtTrabajadorVenta.setText(rs.getString(1)+" "+rs.getString(2)+" "+rs.getString(3));
                }
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, "Error SQL");
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnBuscarDatosActionPerformed

    private void btnISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnISBNActionPerformed
        // TODO add your handling code here:
        InsertarISBN x= new InsertarISBN();
        x.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnISBNActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if(boxBoletaVenta.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null, "No selecciono una boleta, seleccione una y verifique los datos");
        }
        else
        {
            x=new conexion();
            try
            {
                Connection cn=x.getConnection();
                Statement st=cn.createStatement();
                ResultSet rs, rs2;
                
                int i, codigo = 0;
                rs2=st.executeQuery("select * from boleta where folio_boleta="+boxBoletaVenta.getSelectedItem()+"");
                if(rs2.next())
                {
                    codigo=Integer.parseInt(rs2.getString(4));
                }
                rs=st.executeQuery("select * from boleta where folio_boleta="+boxBoletaVenta.getSelectedItem()+"");
                if(rs.next())
                {
                    i=st.executeUpdate("insert into venta values ('"+rs.getString(5)+"', "+rs.getString(1)+", '"+rs.getString(6)+"', "+rs.getString(4)+")");
                    if(i!=0)
                    {
                        i=st.executeUpdate("update boleta set etsado='vendida' where folio_boleta="+boxBoletaVenta.getSelectedItem()+"");
                        i=st.executeUpdate("update libro set estado='Vendido' where numero_serie="+codigo+"");
                        JOptionPane.showMessageDialog(null, "Venta realizada!");
                        
                        
                        boxBoletaVenta.removeAllItems();
                        boxBoletaVenta.addItem("Boleta");
                        
                        ArrayList <String> listaBoletas=new ArrayList <String>();
                        listaBoletas=llenarListaBoletas();
        
                        for(int is=0; is<listaBoletas.size(); is++)
                        {
                             boxBoletaVenta.addItem(listaBoletas.get(is));
                        }
                        
                        ComboBoxLibro.removeAllItems();
                        ComboBoxLibro.addItem("Libro");
                    
                         ArrayList <String> listaLibros=new ArrayList <String>();
                        listaLibros=llenarListaLibros();
        
                        for(int is=0; is<listaLibros.size(); is++)
                        {
                             ComboBoxLibro.addItem(listaLibros.get(is));
                        }
                        btnCancelarActionPerformed(evt);
                    }
                }
            }
            catch(SQLException ex)
            {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txtDistribuidorCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDistribuidorCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDistribuidorCompraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(ComboBoxFactura.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null, "No selecciono una factura, seleccione una y verifique los datos");
        }
        else
        {
            x=new conexion();
            try
            {
                Connection cn=x.getConnection();
                Statement st=cn.createStatement();
                ResultSet rs, rs2;
                
                int i, codigo = 0;
                rs2=st.executeQuery("select * from factura where folio_factura="+ComboBoxFactura.getSelectedItem()+"");
                if(rs2.next())
                {
                    codigo=Integer.parseInt(rs2.getString(3));
                }
                rs=st.executeQuery("select * from factura where folio_factura="+ComboBoxFactura.getSelectedItem()+"");
                if(rs.next())
                {
                    int folio=Integer.parseInt(rs.getString(1));
                    int idLibro=Integer.parseInt(rs.getString(3));
                    i=st.executeUpdate("insert into compra values ('"+rs.getString(5)+"', "+folio+", "+rs.getString(3)+")");
                    
                    if(i!=0)
                    {
                        JOptionPane.showMessageDialog(null, "Compra realizada!");
                        st.executeUpdate("update mydb.factura set estado='comprada' where folio_factura="+folio+"");
                        st.executeUpdate("update libro set estado='Disponible' where libro.numero_serie="+idLibro+"");
                        
                        ComboBoxFactura.removeAllItems();
                        ComboBoxFactura.addItem("Factura");
                        
                        ArrayList <String> listaFacturas=new ArrayList <String>();
                        listaFacturas=llenarListaFacturas();
        
                        for(int is=0; is<listaFacturas.size(); is++)
                        {
                             ComboBoxFactura.addItem(listaFacturas.get(is));
                        }
                        
                        ComboBoxLibro.removeAllItems();
                        ComboBoxLibro.addItem("Libro");
                    
                         ArrayList <String> listaLibros=new ArrayList <String>();
                        listaLibros=llenarListaLibros();
        
                        for(int is=0; is<listaLibros.size(); is++)
                        {
                             ComboBoxLibro.addItem(listaLibros.get(is));
                        }
                        jButton8ActionPerformed(evt);
                    }
                }
            }
            catch(SQLException ex)
            {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if(ComboBoxFactura.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null, "No selecciono una factura para la compra");
        }
        else
        {
            Connection cn=x.getConnection();
            try
            {
                Statement st=cn.createStatement();
                ResultSet rs;
                int libro=0;
                String distribuidor = null;
                
                rs=st.executeQuery("select * from factura where folio_factura="+ComboBoxFactura.getSelectedItem()+"");
                if(rs.next())
                {
                    libro=Integer.parseInt(rs.getString(3));
                    distribuidor=rs.getString(5);
                }
                rs=st.executeQuery("select titutlo from libro where numero_serie="+libro+"");
                if(rs.next())
                {
                    txtLibroCompra.setText(rs.getString(1));
                }
                rs=st.executeQuery("select nombre_distribuidor from distribuidor where rut_distribuidor='"+distribuidor+"'");
                if(rs.next())
                {
                    txtDistribuidorCompra.setText(rs.getString(1));
                }
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, "Error SQL");
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        
        Entrega x=new Entrega();
        x.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        // TODO add your handling code here:
        String id, fechaArriendo="", fechaDevolucion="";
        int idLibro = 0, dia, mes, anio;
        boolean sw=true;
        
        if(ComboBoxLibro.getSelectedIndex()==0)
        {
         JOptionPane.showMessageDialog(null, "No ha seleccionado un libro");
         sw=false;
        }
        else
        {
            id=String.valueOf(ComboBoxLibro.getSelectedItem());
            idLibro=Integer.parseInt(id);
        }
        
        
        try
        {
            dia=calendarioArriendo.getCalendar().get(Calendar.DAY_OF_MONTH);
            mes=calendarioArriendo.getCalendar().get(Calendar.MONTH)+1;
            anio=calendarioArriendo.getCalendar().get(Calendar.YEAR);
            fechaArriendo=(dia+"-"+mes+"-"+anio);
            dia=calendarioDevolucion.getCalendar().get(Calendar.DAY_OF_MONTH);
            mes=calendarioDevolucion.getCalendar().get(Calendar.MONTH)+1;
            anio=calendarioDevolucion.getCalendar().get(Calendar.YEAR);
            fechaDevolucion=(dia+"-"+mes+"-"+anio);
            
        }
        catch(NullPointerException ex)
        {
            JOptionPane.showMessageDialog(null, "Fecha ingresada no es valida, verifiquelas");
            sw=false;
        }
        
        if(ComboCliente.getSelectedIndex()==0 || ComboTrabajador.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null, "No selecciono cliente o trabajador");
            sw=false;
        }
        
        if(sw==true)
        {
            try
            {
                x=new conexion();
                Connection cn=x.getConnection();
                Statement st=cn.createStatement();
                int i;
                
                i=st.executeUpdate("insert into arriendo (fecha_arriendo, fecha_devolucion, fecha_entrega, dias_atraso, costo_atraso, Trabajador_rut_trabajador, Libro_numero_serie, Cliente_rut_cliente) values ('"+fechaArriendo+"','"+fechaDevolucion+"', null, null, null, '"+ComboTrabajador.getSelectedItem()+"', "+ComboBoxLibro.getSelectedItem()+", '"+ComboCliente.getSelectedItem()+"')");
                
                if(i!=0)
                {
                    st.executeUpdate("update libro set estado='Arrendado' where numero_serie="+idLibro+"");
                    JOptionPane.showMessageDialog(null, "Libro arrendado");
                    
                    btnCancelarArriendoActionPerformed(evt);
                    ComboBoxLibro.removeAllItems();
                        ComboBoxLibro.addItem("Libro");
                    
                         ArrayList <String> listaLibros=new ArrayList <String>();
                        listaLibros=llenarListaLibros();
        
                        for(int is=0; is<listaLibros.size(); is++)
                        {
                             ComboBoxLibro.addItem(listaLibros.get(is));
                        }
                }
            }
            catch(SQLException ex)
            {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        Principal x=new Principal ();
        x.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        MostrarClienteTrabajador.MostrarCliente x= new MostrarCliente();
        x.setDefaultCloseOperation(HIDE_ON_CLOSE);
        x.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        MostrarClienteTrabajador.MostrarTrabajador x= new MostrarTrabajador();
        x.setDefaultCloseOperation(HIDE_ON_CLOSE);
        x.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        Ventas x=new Ventas();
        x.setDefaultCloseOperation(HIDE_ON_CLOSE);
        x.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        Arriendo x=new Arriendo();
        x.setDefaultCloseOperation(HIDE_ON_CLOSE);
        x.setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        Compras x=new Compras();
        x.setDefaultCloseOperation(HIDE_ON_CLOSE);
        x.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuOpciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarBoleta;
    private javax.swing.JButton AgregarFactura;
    private javax.swing.JComboBox<String> ComboBoxFactura;
    private javax.swing.JComboBox<String> ComboBoxLibro;
    private javax.swing.JComboBox<String> ComboCliente;
    private javax.swing.JComboBox<String> ComboTrabajador;
    private javax.swing.ButtonGroup botonesLibro;
    private javax.swing.JComboBox<String> boxBoletaVenta;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAutor;
    private javax.swing.JButton btnBuscarDatos;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarArriendo;
    private javax.swing.JButton btnCategoria;
    private javax.swing.JButton btnEditorial;
    private javax.swing.JButton btnISBN;
    private javax.swing.JButton btnIdioma;
    private com.toedter.calendar.JDateChooser calendarioArriendo;
    private com.toedter.calendar.JDateChooser calendarioDevolucion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton radioBuscar;
    private javax.swing.JRadioButton radioBuscar1;
    private javax.swing.JRadioButton radioBuscar2;
    private javax.swing.JRadioButton radioBuscar3;
    private javax.swing.JRadioButton radioBuscar4;
    private javax.swing.JRadioButton radioBuscar5;
    private javax.swing.JRadioButton radioEliminar;
    private javax.swing.JRadioButton radioEliminar1;
    private javax.swing.JRadioButton radioEliminar2;
    private javax.swing.JRadioButton radioEliminar3;
    private javax.swing.JRadioButton radioEliminar4;
    private javax.swing.JRadioButton radioEliminar5;
    private javax.swing.JRadioButton radioInsertar;
    private javax.swing.JRadioButton radioInsertar1;
    private javax.swing.JRadioButton radioInsertar2;
    private javax.swing.JRadioButton radioInsertar3;
    private javax.swing.JRadioButton radioInsertar4;
    private javax.swing.JRadioButton radioInsertar5;
    private javax.swing.JRadioButton radioModificar;
    private javax.swing.JRadioButton radioModificar1;
    private javax.swing.JRadioButton radioModificar2;
    private javax.swing.JRadioButton radioModificar3;
    private javax.swing.JRadioButton radioModificar4;
    private javax.swing.JRadioButton radioModificar5;
    private javax.swing.JRadioButton radioMostrarTodos;
    private javax.swing.JRadioButton radioMostrarTodos1;
    private javax.swing.JRadioButton radioMostrarTodos2;
    private javax.swing.JRadioButton radioMostrarTodos3;
    private javax.swing.JRadioButton radioMostrarTodos4;
    private javax.swing.JRadioButton radioMostrarTodos5;
    private javax.swing.JTextField txtClienteVenta;
    private javax.swing.JTextField txtDistribuidorCompra;
    private javax.swing.JTextField txtLibroCompra;
    private javax.swing.JTextField txtLibroVenta;
    public javax.swing.JTextField txtTrabajadorVenta;
    // End of variables declaration//GEN-END:variables
}
