/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Factura;

import Autor.*;
import Distribuidor.EliminarDistribuidor;
import Libro.*;
import Pantallas.MenuOpciones;
import Pantallas.conexion;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author 20017181-0
 */
public class BuscarFactura extends javax.swing.JFrame {

    /**
     * Creates new form BuscarLibro
     */
    DefaultTableModel modeloBuscarFactura;
    conexion x=new conexion();
    public BuscarFactura() {
        modeloBuscarFactura= new DefaultTableModel(null, getColumnas());
        setFilas();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesBusqueda = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radioFolio = new javax.swing.JRadioButton();
        radioDistribuidor = new javax.swing.JRadioButton();
        radioMetodoPago = new javax.swing.JRadioButton();
        radioFecha = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscado = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        botonesBusqueda.add(radioFolio);
        radioFolio.setText("Folio");

        botonesBusqueda.add(radioDistribuidor);
        radioDistribuidor.setText("Distribuidor");

        botonesBusqueda.add(radioMetodoPago);
        radioMetodoPago.setText("Metodo de Pago");
        radioMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMetodoPagoActionPerformed(evt);
            }
        });

        botonesBusqueda.add(radioFecha);
        radioFecha.setText("Fecha");

        jLabel1.setText("Texto a Buscar");

        txtBuscado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscadoKeyTyped(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jTable1.setModel(modeloBuscarFactura);
        jTable1.setEnabled(false);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioFolio)
                            .addComponent(radioMetodoPago)
                            .addComponent(radioDistribuidor)
                            .addComponent(radioFecha)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(radioFolio)
                .addGap(18, 18, 18)
                .addComponent(radioDistribuidor)
                .addGap(18, 18, 18)
                .addComponent(radioMetodoPago)
                .addGap(18, 18, 18)
                .addComponent(radioFecha)
                .addGap(114, 114, 114)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addComponent(btnVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

            private String [] getColumnas()
    {
        String columna[]= new String [] {"FOLIO","PRECIO NETO","IVA","PRECIO BRUTO","LIBRO","DISTRIBUIDOR","METODO DE PAGO","FECHA FACTURA"};
        
        return columna;
    }
    
    private void setFilas()
    {
        try
        {
            Connection cn=x.getConnection();
            Statement st=cn.createStatement();
            ResultSet rs;
            rs=st.executeQuery("select factura.folio_factura, documento.precio_neto, documento.iva, documento.precio_bruto, libro.titutlo, factura.Distribuidor, factura.Metodo_Pago, factura.fecha_compra from libro join factura on factura.Libro_numero_serie=libro.numero_serie join documento on documento.Factura_folio_factura=factura.folio_factura");
            
            Object datos[]=new Object[8];
            
            while(rs.next())
            {
                for(int i=0; i<8; i++)
                {
                    datos[i]=rs.getObject(i+1);
                }
                modeloBuscarFactura.addRow(datos);
            }
            
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(EliminarDistribuidor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void radioMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMetodoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMetodoPagoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        
        MenuOpciones x=new MenuOpciones();
        x.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed
    TableRowSorter trs;
    private void txtBuscadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadoKeyTyped
        // TODO add your handling code here:
        if(radioDistribuidor.isSelected() || radioFecha.isSelected() || radioFolio.isSelected() || radioMetodoPago.isSelected())
        {
            
            
            if(radioDistribuidor.isSelected())
            {
              txtBuscado.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) 
                {
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscado.getText(), 5));
                }
                });  
            }
            if(radioFecha.isSelected())
            {
              txtBuscado.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) 
                {
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscado.getText(), 7));
                }
                });  
            }
            if(radioFolio.isSelected())
            {
              txtBuscado.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) 
                {
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscado.getText(), 0));
                }
                });  
            }
            if(radioMetodoPago.isSelected())
            {
              txtBuscado.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) 
                {
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscado.getText(), 6));
                }
                });  
            }
            
            trs=new TableRowSorter(modeloBuscarFactura);
            jTable1.setRowSorter(trs);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No selecciono porque opcion filtrar");
        }
    }//GEN-LAST:event_txtBuscadoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botonesBusqueda;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton radioDistribuidor;
    private javax.swing.JRadioButton radioFecha;
    private javax.swing.JRadioButton radioFolio;
    private javax.swing.JRadioButton radioMetodoPago;
    private javax.swing.JTextField txtBuscado;
    // End of variables declaration//GEN-END:variables
}
