/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Factura;

import Pantallas.MenuOpciones;
import Pantallas.Nuevo_Usuario;
import Pantallas.conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 20017181-0
 */
public class MostrarModificar extends javax.swing.JFrame {

    /**
     * Creates new form InsertarLibro
     */
    conexion x;
    public MostrarModificar() {
        initComponents();
        this.setLocationRelativeTo(null);
        Date now = new Date(System.currentTimeMillis());
        calendarioFactura.setMaxSelectableDate(now);
        
        ArrayList <String> listaDistribuidor=new ArrayList <String>();
        ArrayList <String> listaLibro=new ArrayList <String>();
        listaDistribuidor=llenarListaDistribuidor();
        listaLibro=llenarListaLibro();
        
        for(int i=0; i<listaDistribuidor.size(); i++)
        {
            ComboBoxDistribuidor.addItem(listaDistribuidor.get(i));
        }
        for(int i=0; i<listaLibro.size(); i++)
        {
            ComboBoxLibro.addItem(listaLibro.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNeto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ComboBoxDistribuidor = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        ComboBoxMetodoPago = new javax.swing.JComboBox<>();
        calendarioFactura = new com.toedter.calendar.JDateChooser();
        ComboBoxLibro = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtDistribuidor = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Folio");

        txtFolio.setEnabled(false);

        jLabel2.setText("Precio Neto");

        txtNeto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNetoKeyTyped(evt);
            }
        });

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha Compra");

        jLabel7.setText("Distribuidor Involucrado");

        ComboBoxDistribuidor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Distribuidor" }));
        ComboBoxDistribuidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxDistribuidorActionPerformed(evt);
            }
        });

        jLabel8.setText("Metodo de Pago");

        ComboBoxMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metodo de Pago", "Efectivo", "Tarjeta de Credito", "Tarjeta de Debito" }));
        ComboBoxMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMetodoPagoActionPerformed(evt);
            }
        });

        ComboBoxLibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libro" }));
        ComboBoxLibro.setEnabled(false);

        jLabel5.setText("Libro Comprado");

        txtDistribuidor.setEnabled(false);

        jButton3.setText("Mostrar Dato");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(590, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel8))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboBoxMetodoPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboBoxDistribuidor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFolio)
                            .addComponent(txtNeto)
                            .addComponent(calendarioFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDistribuidor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calendarioFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxDistribuidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtDistribuidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(107, 107, 107)
                .addComponent(btnVolver)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        public ArrayList llenarListaDistribuidor()
    {
        ArrayList <String> lista=new ArrayList <String>();
        x=new conexion();
        Connection cn=x.getConnection();
        try 
        {
            Statement st=cn.createStatement();
            ResultSet rs;
            rs=st.executeQuery("select rut_distribuidor from mydb.distribuidor");
            
            while(rs.next())
            {
                lista.add(rs.getString(1));
            }
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(Nuevo_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        return lista;
    }
        
     public ArrayList llenarListaLibro()
    {
        ArrayList <String> lista=new ArrayList <String>();
        x=new conexion();
        Connection cn=x.getConnection();
        try 
        {
            Statement st=cn.createStatement();
            ResultSet rs;
            rs=st.executeQuery("select numero_serie from mydb.libro");
            
            while(rs.next())
            {
                lista.add(rs.getString(1));
            }
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(Nuevo_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        return lista;
    }
    
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        BuscarFolioFactura x=new BuscarFolioFactura();
        x.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtNeto.setText("");
        calendarioFactura.setCalendar(null);
        ComboBoxDistribuidor.setSelectedIndex(0);
        ComboBoxMetodoPago.setSelectedIndex(0);
        txtNeto.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ComboBoxDistribuidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxDistribuidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxDistribuidorActionPerformed

    private void ComboBoxMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxMetodoPagoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ComboBoxMetodoPagoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int folio=0, precioNeto=0, precioBruto, iva;
        String fecha="", id;
        int  dia, mes, anio, idLibro;
        
        boolean sw=true;
        
        
        try
        {
            folio=Integer.parseInt(txtFolio.getText());
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "Folio ingresado no es numerico entero.");
            sw=false;
        }
        
        try
        {
            precioNeto=Integer.parseInt(txtNeto.getText());
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "Precio neto ingresado no es numerico entero.");
            sw=false;
        }
        
        try
        {
            dia=calendarioFactura.getCalendar().get(Calendar.DAY_OF_MONTH);
            mes=calendarioFactura.getCalendar().get(Calendar.MONTH)+1;
            anio=calendarioFactura.getCalendar().get(Calendar.YEAR);
            fecha=(dia+"-"+mes+"-"+anio);
        }
        catch(NullPointerException ex)
        {
            JOptionPane.showMessageDialog(null, "Fecha no valida");
            sw=false;
        }
        
        if(ComboBoxLibro.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null, "No selecciono un libro para la factura");
            sw=false;
        }
        
        if(ComboBoxMetodoPago.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null, "No selecciono un metodo de pago");
            sw=false;
        }
        if(ComboBoxDistribuidor.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null, "No se selecciono un distribuidor.");
            sw=false;
        }
        
        if(sw==true)
        {
            id=String.valueOf(ComboBoxLibro.getSelectedItem());
            idLibro=Integer.parseInt(id);
            Connection cn=x.getConnection();
            try 
            {
                Statement st=cn.createStatement();
                ResultSet rs;
                int i;
                
                i=st.executeUpdate("update mydb.factura set fecha_compra='"+fecha+"', Metodo_pago='"+ComboBoxMetodoPago.getSelectedItem()+"', Distribuidor='"+ComboBoxDistribuidor.getSelectedItem()+"' where folio_factura="+folio+"");
                
                if(i!=0)
                {
                    iva=precioNeto*19/100;
                    precioBruto=precioNeto+iva;
                    
                    st.executeUpdate("update mydb.documento set precio_bruto="+precioBruto+", precio_neto="+precioNeto+", iva="+iva+" where Factura_folio_factura="+folio+"");
                    
                    JOptionPane.showMessageDialog(null, "Factura actualizada con exito");
                    MenuOpciones x=new MenuOpciones();
                    x.setVisible(true);
                    dispose();
                }
            } 
            catch (SQLException ex) 
            {
                JOptionPane.showMessageDialog(null, "Factura que intenta ingresar ya se encuentra en la BD");
                System.out.println(ex.getMessage());
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String rutDistribuidor;
        if(ComboBoxDistribuidor.getSelectedIndex()==0)
        {
                JOptionPane.showMessageDialog(null, "No escogio un distribuidor");
        }
        else
        {
            rutDistribuidor=(String)ComboBoxDistribuidor.getSelectedItem();
            try
            {
                Connection cn=x.getConnection();
                Statement st=cn.createStatement();
                ResultSet rs;
                rs=st.executeQuery("select nombre_distribuidor from distribuidor where rut_distribuidor='"+rutDistribuidor+"'");
                if(rs.next())
                {
                    txtDistribuidor.setText(rs.getString(1));
                }
            }
            catch(SQLException ex)
            {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtNetoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNetoKeyTyped
        // TODO add your handling code here:
        if(txtNeto.getText().length()==9)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtNetoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarModificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> ComboBoxDistribuidor;
    public javax.swing.JComboBox<String> ComboBoxLibro;
    public javax.swing.JComboBox<String> ComboBoxMetodoPago;
    private javax.swing.JButton btnVolver;
    public com.toedter.calendar.JDateChooser calendarioFactura;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDistribuidor;
    public javax.swing.JTextField txtFolio;
    public javax.swing.JTextField txtNeto;
    // End of variables declaration//GEN-END:variables
}
