/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Libro;

import Distribuidor.EliminarDistribuidor;
import Pantallas.MenuOpciones;
import Pantallas.conexion;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author 20017181-0
 */
public class BuscarLibro extends javax.swing.JFrame {

    /**
     * Creates new form BuscarLibro
     */
    DefaultTableModel modeloBuscarLibro;
    conexion x=new conexion();
    public BuscarLibro() {
        
        modeloBuscarLibro= new DefaultTableModel(null, getColumnas());
        setFilas();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesBusqueda = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radioCodigo = new javax.swing.JRadioButton();
        radioNombre = new javax.swing.JRadioButton();
        radioISBN = new javax.swing.JRadioButton();
        radioCategoria = new javax.swing.JRadioButton();
        radioIdioma = new javax.swing.JRadioButton();
        radioEditorial = new javax.swing.JRadioButton();
        radioAutor = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscado = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1279, 507));

        botonesBusqueda.add(radioCodigo);
        radioCodigo.setText("Codigo");

        botonesBusqueda.add(radioNombre);
        radioNombre.setText("Nombre");

        botonesBusqueda.add(radioISBN);
        radioISBN.setText("ISBN");

        botonesBusqueda.add(radioCategoria);
        radioCategoria.setText("Categoria");
        radioCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCategoriaActionPerformed(evt);
            }
        });

        botonesBusqueda.add(radioIdioma);
        radioIdioma.setText("Idioma");

        botonesBusqueda.add(radioEditorial);
        radioEditorial.setText("Editorial");

        botonesBusqueda.add(radioAutor);
        radioAutor.setText("Autor");

        jLabel1.setText("Texto a Buscar");

        txtBuscado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscadoKeyTyped(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jTable1.setModel(modeloBuscarLibro);
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(radioEditorial)
                                        .addComponent(radioIdioma)
                                        .addComponent(radioAutor))
                                    .addGap(9, 9, 9))
                                .addComponent(radioCodigo, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(radioCategoria)
                            .addComponent(radioISBN)
                            .addComponent(radioNombre)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1))
                            .addComponent(txtBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1099, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(radioCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(radioNombre)
                        .addGap(18, 18, 18)
                        .addComponent(radioISBN)
                        .addGap(18, 18, 18)
                        .addComponent(radioCategoria)
                        .addGap(18, 18, 18)
                        .addComponent(radioIdioma)
                        .addGap(18, 18, 18)
                        .addComponent(radioEditorial)
                        .addGap(18, 18, 18)
                        .addComponent(radioAutor)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

            private String [] getColumnas()
    {
        String columna[]= new String [] {"CODIGO","TITULO","NUMERO DE PAGINAS", "PRECIO REFERENCIAL", "AÑO DE PUBLICACION", "ESTADO", "CATEGORIA","IDIOMA", "ISBN", "EDITORIAL", " RUT AUTOR"};
        return columna;
    }
    
    private void setFilas()
    {
        try
        {
            Connection cn=x.getConnection();
            Statement st=cn.createStatement();
            ResultSet rs, rs2;
            rs=st.executeQuery("select numero_serie, titutlo, numero_paginas, precio_referencial, anio_publicacion, estado, Categoria_nombre_categoria, Idioma_nombre_idioma, ISBN_id_isbn, Editorial_nombre_editorial, persona.Autor_rut from libro join libro_autor on libro.numero_serie=libro_autor.Libro_numero_serie join autor on autor.rut=libro_autor.Autor_rut join persona on persona.Autor_rut=autor.rut");
            
            Object datos[]=new Object[11];
            
            while(rs.next())
            {
                for(int i=0; i<11; i++)
                {
                    datos[i]=rs.getObject(i+1);
                }
                modeloBuscarLibro.addRow(datos);
            }
            
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(EliminarDistribuidor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void radioCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCategoriaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        MenuOpciones x=new MenuOpciones();
        x.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed
    TableRowSorter trs;
    private void txtBuscadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadoKeyTyped
        // TODO add your handling code here:
        if(radioAutor.isSelected() || radioCategoria.isSelected() || radioCodigo.isSelected() || radioEditorial.isSelected() || radioISBN.isSelected() || radioIdioma.isSelected() || radioNombre.isSelected())
        {
            
            
            if(radioAutor.isSelected())
            {
              txtBuscado.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) 
                {
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscado.getText(), 10));
                }
                });  
            }
            
            if(radioCategoria.isSelected())
            {
              txtBuscado.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) 
                {
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscado.getText(), 6));
                }
                });  
            }
            if(radioCodigo.isSelected())
            {
              txtBuscado.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) 
                {
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscado.getText(), 0));
                }
                });  
            }
            
            if(radioEditorial.isSelected())
            {
              txtBuscado.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) 
                {
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscado.getText(), 9));
                }
                });  
            }
            
            if(radioISBN.isSelected())
            {
              txtBuscado.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) 
                {
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscado.getText(), 8));
                }
                });  
            }
            
            if(radioIdioma.isSelected())
            {
              txtBuscado.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) 
                {
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscado.getText(), 7));
                }
                });  
            }
            
            if(radioNombre.isSelected())
            {
              txtBuscado.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) 
                {
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscado.getText(), 1));
                }
                });  
            }
            
            trs=new TableRowSorter(modeloBuscarLibro);
            jTable1.setRowSorter(trs);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No selecciono porque opcion filtrar");
        }
    }//GEN-LAST:event_txtBuscadoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botonesBusqueda;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton radioAutor;
    private javax.swing.JRadioButton radioCategoria;
    private javax.swing.JRadioButton radioCodigo;
    private javax.swing.JRadioButton radioEditorial;
    private javax.swing.JRadioButton radioISBN;
    private javax.swing.JRadioButton radioIdioma;
    private javax.swing.JRadioButton radioNombre;
    private javax.swing.JTextField txtBuscado;
    // End of variables declaration//GEN-END:variables
}
