/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trabajador;

import Factura.*;
import Autor.*;
import Distribuidor.EliminarDistribuidor;
import Libro.*;
import Pantallas.MenuOpciones;
import Pantallas.conexion;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author 20017181-0
 */
public class BuscarTrabajador extends javax.swing.JFrame {

    /**
     * Creates new form BuscarLibro
     */
    DefaultTableModel modeloBuscarFactura;
    conexion x=new conexion();
    public BuscarTrabajador() {
        modeloBuscarFactura= new DefaultTableModel(null, getColumnas());
        setFilas();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesBusqueda = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        radioRut = new javax.swing.JRadioButton();
        radioApMaterno = new javax.swing.JRadioButton();
        radioApPaterno = new javax.swing.JRadioButton();
        radioFecha = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscado = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        radioNombre = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        botonesBusqueda.add(radioRut);
        radioRut.setText("RUT");

        botonesBusqueda.add(radioApMaterno);
        radioApMaterno.setText("Apellido Materno");

        botonesBusqueda.add(radioApPaterno);
        radioApPaterno.setText("Apellido Paterno");
        radioApPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioApPaternoActionPerformed(evt);
            }
        });

        botonesBusqueda.add(radioFecha);
        radioFecha.setText("Fecha Contrato");

        jLabel1.setText("Texto a Buscar");

        txtBuscado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscadoKeyTyped(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jTable1.setModel(modeloBuscarFactura);
        jTable1.setEnabled(false);
        jScrollPane2.setViewportView(jTable1);

        botonesBusqueda.add(radioNombre);
        radioNombre.setText("Nombre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(radioApPaterno)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(radioRut)
                                .addComponent(radioApMaterno)
                                .addComponent(radioNombre)
                                .addComponent(radioFecha)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(radioRut)
                        .addGap(16, 16, 16)
                        .addComponent(radioNombre)
                        .addGap(18, 18, 18)
                        .addComponent(radioApPaterno)
                        .addGap(18, 18, 18)
                        .addComponent(radioApMaterno)
                        .addGap(18, 18, 18)
                        .addComponent(radioFecha)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(btnVolver)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

            private String [] getColumnas()
    {
        String columna[]= new String [] {"RUT","NOMBRE","APELLIDO PATERNO","APELLIDO MATERNO","FECHA CONTRATO","DIRECCION","TELEFONO","CORREO"};
        
        return columna;
    }
    
    private void setFilas()
    {
        try
        {
            Connection cn=x.getConnection();
            Statement st=cn.createStatement();
            ResultSet rs;
            rs=st.executeQuery("select rut_trabajador, persona.nombre_persona, persona.apellido_paterno, persona.apellido_materno, fecha_contrato, direccion, numero_telefono, correo from persona join trabajador on persona.Trabajador_rut_trabajador=trabajador.rut_trabajador join correos on correos.id_correo=trabajador.Correos_id_correo join direccion on direccion.id_direccion=trabajador.Direccion_id_direccion join telefono on telefono.id_telefono=trabajador.Telefono_id_telefono");
            
            Object datos[]=new Object[8];
            
            while(rs.next())
            {
                for(int i=0; i<8; i++)
                {
                    datos[i]=rs.getObject(i+1);
                }
                modeloBuscarFactura.addRow(datos);
            }
            
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(EliminarDistribuidor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void radioApPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioApPaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioApPaternoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        
        MenuOpciones x=new MenuOpciones();
        x.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed
    TableRowSorter trs;
    private void txtBuscadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadoKeyTyped
        // TODO add your handling code here:
        if(radioApMaterno.isSelected() || radioFecha.isSelected() || radioRut.isSelected() || radioApPaterno.isSelected() || radioNombre.isSelected())
        {
            if(radioApMaterno.isSelected())
            {
              txtBuscado.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) 
                {
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscado.getText(), 3));
                }
                });  
            }
            if(radioFecha.isSelected())
            {
              txtBuscado.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) 
                {
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscado.getText(), 4));
                }
                });  
            }
            if(radioRut.isSelected())
            {
              txtBuscado.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) 
                {
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscado.getText(), 0));
                }
                });  
            }
            if(radioApPaterno.isSelected())
            {
              txtBuscado.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) 
                {
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscado.getText(), 2));
                }
                });  
            }
            if(radioNombre.isSelected())
            {
              txtBuscado.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) 
                {
                    trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBuscado.getText(), 1));
                }
                });  
            }
            
            trs=new TableRowSorter(modeloBuscarFactura);
            jTable1.setRowSorter(trs);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No selecciono porque opcion filtrar");
        }
    }//GEN-LAST:event_txtBuscadoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarTrabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botonesBusqueda;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton radioApMaterno;
    private javax.swing.JRadioButton radioApPaterno;
    private javax.swing.JRadioButton radioFecha;
    private javax.swing.JRadioButton radioNombre;
    private javax.swing.JRadioButton radioRut;
    private javax.swing.JTextField txtBuscado;
    // End of variables declaration//GEN-END:variables
}
